global: &global
    environment:
        MAJOR_VERSION: 0
        MINOR_VERSION: 0
        PROJECT_NAME: nicknames
    docker:
        - image: podshivalovilya/cppbuilder:latest
    working_directory: /usr/local/src

version: 2
jobs:
    build:
        <<: *global
        steps:
            - checkout
            - run:
                name: "CMake project"
                command: "cmake ."
            - run:
                name: "Building"
                command: "cmake --build ."
            - run:
                name: "Running tests"
                command: "cmake --build . --target test"
            - run:
                name: "Running packaging"
                command: "cmake --build . --target package"
            - persist_to_workspace:
                root: ./
                paths:
                    - ./*.deb
    deploy:
        <<: *global
        steps:
            - attach_workspace:
                at: ./
            - run:
                name: "Deploying to bintray"
                command: |
                    ls -lh && \
                    export PACKAGE_NAME=${PROJECT_NAME}-${MAJOR_VERSION}.${MINOR_VERSION}.${CIRCLE_PREVIOUS_BUILD_NUM}-Linux.deb && \
                    curl -T ${PACKAGE_NAME} -u${USER}:${BINTRAY_API_KEY} "https://api.bintray.com/content/${USER}/${REPO_PATH}/${CIRCLE_PREVIOUS_BUILD_NUM}/${PACKAGE_NAME};deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
workflows:
    version: 2
    build_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: /master$/
